networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

services:
  payment-gateway:
    build:
      context: ../../src/PaymentGateway
      dockerfile: Dockerfile
      args:
        - DOTNET_VERSION=8.0
      platforms:
        - linux/amd64
      no_cache: true
    container_name: payment-gateway
    hostname: payment-gateway
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=SimpliPay;User Id=postgres;Password=postgres;Timeout=15;Pooling=true;MinPoolSize=1;MaxPoolSize=20;ConnectionLifeTime=15;
      - Kafka__Server=kafka:9092
      - Kafka__GroupId=payment-gateway-00
      - Kafka__Topic=events.simplipay.payments
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
      no_cache: true
    container_name: postgres
    hostname: postgres
    restart: on-failure
    stop_grace_period: 30s
    environment:
      POSTGRES_DB: SimpliPay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 512M
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - backend
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      retries: 20
      interval: 10s
    
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend
    depends_on:
      zookeeper:
        condition: service_healthy

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    hostname: kafdrop
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks: 
      - backend
    depends_on:
      - kafka
